version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.11.2

    steps:
      - checkout

      - restore_cache:
          keys:
          # Partial match to always find the latest npm tarball cache
          - v1-npm-cache-{{ .Branch }}
          - v1-npm-cache-

      # Install root devDependencies and bootstrap packages
      - run:
          name: Install shared devDependencies
          command: 'npm install --ignore-scripts'

      - run:
          name: Lerna Bootstrap
          command: 'npm run bootstrap'

      # Cache a bunch of stuff
      # - npm's local tarball cache
      # - node_modules for each package (npm is fast at restoring from a partially-outdated tree)
      - save_cache:
          paths:
            - ~/.npm
            - /root/.npm
            - node_modules
            - packages/peregrine/node_modules
            - packages/pwa-buildpack/node_modules
            - venia-concept/node_modules
          key: v1-npm-cache-{{ .Branch }}

      - run:
          name: ESLint
          command: 'npm run lint'

      - run:
          name: Prettier
          command: 'npm run prettier:check'

      - run:
          name: Unit Tests
          command: 'npm test -- -i'

      - store_artifacts:
          path: coverage
