version: 2
workflows:
  version: 2
  build-deploy:
    jobs:
      - pr:
          filters:
            branches:
              ignore: &integration_branches
                - master
                - develop
                - /release\/\d+\.\d+
      - integration:
          filters:
            branches:
              only: *integration_branches

# This key means nothing to CircleCI; it's just a place to keep anchored
# configuration nodes for reuse.
common_settings:
  docker: &docker_setup
    - image: 'circleci/node:10.14.1'
  save_cache: &savecache
    name: Save yarn package cache
    key: 'yarn-packages-{{ checksum "yarn.lock" }}'
    paths:
      - ~/.cache/yarn
  install_packages: &install_packages
    name: Install packages from lockfile
    # Don't ignore scripts. Bundlesize needs to build iltorb on install.
    command: yarn install --frozen-lockfile

  full_build: &full_build
    name: Full build
    command: 'cp packages/venia-concept/.env.dist packages/venia-concept/.env && yarn run clean:dist && yarn run build'

  storybook_build: &storybook_build
    name: Storybook compilation
    command: yarn workspace @magento/venia-concept run storybook:build

  test_result_path: &test_result_path
    path: "test-results"

  artifact_storage_path: &artifact_storage_path
    path: "packages/venia-concept/dist"

jobs:
  integration:
    docker: *docker_setup
    steps:
      - checkout
      - run: *install_packages
      - run:
          name: Test suites
          command: 'yarn run test:ci'
      - run:
          name: Coveralls coverage analysis
          command: yarn run coveralls
      - run: *full_build
      - run: *storybook_build
      - run:
          name: Bundle size analysis
          command: yarn run bundlesize

      - store_test_results: *test_result_path
      - store_artifacts: *artifact_storage_path
  pr:
    docker: *docker_setup
    steps:
      - checkout
      - restore_cache:
          keys:
            - 'yarn-packages-{{ checksum "yarn.lock" }}'
      - run: *install_packages
      - save_cache: *savecache
      - run:
          name: Test suites and coverage
          # Test failures should not stop Danger, so hide the exit code.
          command: 'yarn run test:ci && yarn run coveralls || true'
      - run: *full_build
      - run: *storybook_build
      - run:
          name: DangerCI
          command: yarn run danger
      - run:
          name: Bundle size analysis
          command: yarn run bundlesize

      - store_test_results: *test_result_path
      - store_artifacts: *artifact_storage_path
