---
groups: !!pairs
- venia:
    label: "Venia"
    items:
    - "principles"
- foundation:
    label: "Foundation"
    items:
    - "design-tokens"
    - "color"
    - "typography"
- components:
    label: "Components"
    items:
    - "app-bar"
    - "button"
    - "drawer-footer"

pages: !!pairs
- app-bar: "App bar"
- button: "Button"
- color: "Color"
- design-tokens: "Design tokens"
- principles: "Principles"
- typography: "Typography"
- drawer-footer: 'Drawer Footer'
