---
groups: !!pairs
- venia:
    label: "Venia"
    items:
    - "principles"
- foundation:
    label: "Foundation"
    items:
    - "design-tokens"
    - "color"
    - "typography"
- components:
    label: "Components"
    items:
    - "button"

pages: !!pairs
- button: "Button"
- color: "Color"
- design-tokens: "Design tokens"
- principles: "Principles"
- typography: "Typography"
